=== hanka8636/Czlowiek-komputer/Zad1/spisOwiec.dtd
<?xml version="1.0" encoding="utf-8"?>
<?xml encoding="UTF-8"?>

<!ELEMENT spis_owiec (nagłówek,lista_ras,pastwisko+)>
<!ATTLIST spis_owiec
  xmlns CDATA #FIXED ''>

<!ELEMENT nagłówek (data_modyfikacji,autorzy)>
<!ATTLIST nagłówek
  xmlns CDATA #FIXED ''>

<!ELEMENT lista_ras (definicja_rasy)+>
<!ATTLIST lista_ras
  xmlns CDATA #FIXED ''>

<!ELEMENT pastwisko (nazwa,rasa,powierzchnia,stado)>
<!ATTLIST pastwisko
  xmlns CDATA #FIXED ''>

<!ELEMENT data_modyfikacji (#PCDATA)>
<!ATTLIST data_modyfikacji
  xmlns CDATA #FIXED ''>

<!ELEMENT autorzy (autor)+>
<!ATTLIST autorzy
  xmlns CDATA #FIXED ''>

<!ELEMENT definicja_rasy EMPTY>
<!ATTLIST definicja_rasy
  xmlns CDATA #FIXED ''
  identyfikator NMTOKEN #REQUIRED
  nazwa CDATA #REQUIRED>

<!ELEMENT nazwa (#PCDATA)>
<!ATTLIST nazwa
  xmlns CDATA #FIXED ''>

<!ELEMENT rasa EMPTY>
<!ATTLIST rasa
  xmlns CDATA #FIXED ''
  identyfikator NMTOKEN #REQUIRED>

<!ELEMENT powierzchnia (#PCDATA)>
<!ATTLIST powierzchnia
  xmlns CDATA #FIXED ''
  jednostka NMTOKEN #REQUIRED>

<!ELEMENT stado (owca)+>
<!ATTLIST stado
  xmlns CDATA #FIXED ''>

<!ELEMENT autor (imię,nazwisko,album,mail)>
<!ATTLIST autor
  xmlns CDATA #FIXED ''>

<!ELEMENT owca (id,imie,data_ur,plec,waga,dlugosc_runa,opis,
                szybkosc_marszu,szybkosc_zjadania_trawy)>
<!ATTLIST owca
  xmlns CDATA #FIXED ''>

<!ELEMENT imię (#PCDATA)>
<!ATTLIST imię
  xmlns CDATA #FIXED ''>

<!ELEMENT nazwisko (#PCDATA)>
<!ATTLIST nazwisko
  xmlns CDATA #FIXED ''>

<!ELEMENT album (#PCDATA)>
<!ATTLIST album
  xmlns CDATA #FIXED ''>

<!ELEMENT mail (#PCDATA)>
<!ATTLIST mail
  xmlns CDATA #FIXED ''>

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
  xmlns CDATA #FIXED ''>

<!ELEMENT imie (#PCDATA)>
<!ATTLIST imie
  xmlns CDATA #FIXED ''>

<!ELEMENT data_ur (#PCDATA)>
<!ATTLIST data_ur
  xmlns CDATA #FIXED ''>

<!ELEMENT plec (#PCDATA)>
<!ATTLIST plec
  xmlns CDATA #FIXED ''>

<!ELEMENT waga (#PCDATA)>
<!ATTLIST waga
  xmlns CDATA #FIXED ''
  jednostka NMTOKEN #REQUIRED>

<!ELEMENT dlugosc_runa (#PCDATA)>
<!ATTLIST dlugosc_runa
  xmlns CDATA #FIXED ''
  jednostka NMTOKEN #REQUIRED>

<!ELEMENT opis (#PCDATA)>
<!ATTLIST opis
  xmlns CDATA #FIXED ''>

<!ELEMENT szybkosc_marszu (#PCDATA)>
<!ATTLIST szybkosc_marszu
  xmlns CDATA #FIXED ''
  jednostka CDATA #REQUIRED>

<!ELEMENT szybkosc_zjadania_trawy (#PCDATA)>
<!ATTLIST szybkosc_zjadania_trawy
  xmlns CDATA #FIXED ''
  jednostka CDATA #REQUIRED>

=== hanka8636/Czlowiek-komputer/Zad1/spisOwiec.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="spisOwiec.css"?>
<!DOCTYPE plany SYSTEM "spisOwiec.dtd" [] >
<spis_owiec>

  <nagłówek>
    <data_modyfikacji>2018-03-05</data_modyfikacji>
    <autorzy>
      <autor>
        <imię>Hanna</imię>
        <nazwisko>Paluszkiewicz</nazwisko>
        <album>203962</album>
        <mail>203962@edu.p.lodz.pl</mail>
      </autor>
      <autor>
        <imię>Aneta</imię>
        <nazwisko>Wiśniewska</nazwisko>
        <album>204029</album>
        <mail>204029@edu.p.lodz.pl</mail>
      </autor>
    </autorzy>
  </nagłówek>

  <lista_ras>
    <definicja_rasy nazwa="Białogłowa Owca Mięsna" identyfikator="O1"/>
    <definicja_rasy nazwa="Corriedale" identyfikator="O2"/>
    <definicja_rasy nazwa="Dorset Horn" identyfikator="O3"/>
    <definicja_rasy nazwa="Owca Fryzyjska" identyfikator="O4"/>
    <definicja_rasy nazwa="Ile de france" identyfikator="O5"/>
    <definicja_rasy nazwa="Kamieniecka" identyfikator="O6"/>
    <definicja_rasy nazwa="Leine" identyfikator="O7"/>
    <definicja_rasy nazwa="Merynos Polski" identyfikator="O8"/>
    <definicja_rasy nazwa="Merynos Polski odmiana barwna" identyfikator="O9"/>
    <definicja_rasy nazwa="Mouton charollaise" identyfikator="10"/>
    <definicja_rasy nazwa="Odmiana barwna polskiej owcy górskiej" identyfikator="11"/>
    <definicja_rasy nazwa="Odmiana owcy Dorset" identyfikator="12"/>
    <definicja_rasy nazwa="Olkuska" identyfikator="13"/>
    <definicja_rasy nazwa="Owca plenna 09" identyfikator="14"/>
    <definicja_rasy nazwa="Owca plenno-mięsna 08" identyfikator="15"/>
    <definicja_rasy nazwa="Polska owca górska" identyfikator="16"/>
    <definicja_rasy nazwa="Polska owca nizinna" identyfikator="17"/>
    <definicja_rasy nazwa="Polska owca pogórza" identyfikator="18"/>
    <definicja_rasy nazwa="Pomorska" identyfikator="19"/>
    <definicja_rasy nazwa="Romanowska" identyfikator="20"/>
    <definicja_rasy nazwa="Suffolk" identyfikator="21"/>
    <definicja_rasy nazwa="Świniarka" identyfikator="22"/>
    <definicja_rasy nazwa="Texel" identyfikator="23"/>
    <definicja_rasy nazwa="Odmiana Uhruska polskiej owcy nizinnej" identyfikator="24"/>
    <definicja_rasy nazwa="Wielkopolska" identyfikator="25"/>
    <definicja_rasy nazwa="Wrzosówka" identyfikator="26"/>
    <definicja_rasy nazwa="Odmiana żelaźnieńska polskiej owcy nizinnej" identyfikator="27"/>
    <definicja_rasy nazwa="Owca kołudzka" identyfikator="28"/>
    <definicja_rasy nazwa="Owca SCP" identyfikator="29"/>
    <definicja_rasy nazwa="Owca BCP" identyfikator="30"/>
    <definicja_rasy nazwa="Berrichon du cher" identyfikator="31"/>
    <definicja_rasy nazwa="Biała masywu centralnego" identyfikator="32"/>
    <definicja_rasy nazwa="Cakiel podhalański" identyfikator="33"/>
    <definicja_rasy nazwa="Merynos polski w starym typie" identyfikator="34"/>
    <definicja_rasy nazwa="Czarnogłówka" identyfikator="35"/>
  </lista_ras>

  <pastwisko>
    <nazwa>Radosne Pole</nazwa>
    <rasa identyfikator="O1"/>
    <powierzchnia jednostka="ha">125.8</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Wafel</imie>
        <data_ur>2002-09-24</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">50.8</waga>
        <dlugosc_runa jednostka="mm">14.5</dlugosc_runa>
        <opis>
          Elegancki samiec rasy owiec domowych.
        </opis>
        <szybkosc_marszu jednostka="m/s">10.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.4</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>2</id>
        <imie>Masnfred</imie>
        <data_ur>2012-09-22</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">50.1</waga>
        <dlugosc_runa jednostka="mm">12.3</dlugosc_runa>
        <opis>
          Samiec rasy owiec domowych pochodzących z RPA.
        </opis>
        <szybkosc_marszu jednostka="m/s">15.1</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.3</szybkosc_zjadania_trawy>
      </owca>
    </stado>
  </pastwisko>

  <pastwisko>
    <nazwa>Dzikie Pole</nazwa>
    <rasa identyfikator="O2" />
    <powierzchnia jednostka="ha">125.8</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Zosia</imie>
        <data_ur>2002-09-24</data_ur>
        <plec>K</plec>
        <waga jednostka="kg">29.8</waga>
        <dlugosc_runa jednostka="mm">38.5</dlugosc_runa>
        <opis>
          Elegancki i wyrafinowana owca.
        </opis>
        <szybkosc_marszu jednostka="m/s">10.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.4</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>2</id>
        <imie>Pizza</imie>
        <data_ur>2002-09-24</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">60.8</waga>
        <dlugosc_runa jednostka="mm">12.3</dlugosc_runa>
        <opis>
          Owca, która lubi placi.
        </opis>
        <szybkosc_marszu jednostka="m/s">15.1</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.3</szybkosc_zjadania_trawy>
      </owca>
    </stado>
  </pastwisko>

  <pastwisko>
    <nazwa>Pole Huncwotów</nazwa>
    <rasa identyfikator="O3" />
    <powierzchnia jednostka="ha">100.8</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Rosół</imie>
        <data_ur>2012-07-10</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">47.8</waga>
        <dlugosc_runa jednostka="mm">2.5</dlugosc_runa>
        <opis>
          Owca, która panicznie boi się niedziel.
        </opis>
        <szybkosc_marszu jednostka="m/s">30.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.9</szybkosc_zjadania_trawy>
      </owca>
    </stado>
  </pastwisko>

  <pastwisko>
    <nazwa>Alejka róż</nazwa>
    <rasa identyfikator="O4" />
    <powierzchnia jednostka="ha">400.8</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Tropi</imie>
        <data_ur>2003-11-13</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">28.8</waga>
        <dlugosc_runa jednostka="mm">11.5</dlugosc_runa>
        <opis>
          Elegancki tropiciel.
        </opis>
        <szybkosc_marszu jednostka="m/s">5.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">1.0</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>2</id>
        <imie>Tupi</imie>
        <data_ur>2007-02-01</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">52.8</waga>
        <dlugosc_runa jednostka="mm">18.3</dlugosc_runa>
        <opis>
          Strasznie głośno chodzi.
        </opis>
        <szybkosc_marszu jednostka="m/s">28.1</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.1</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>3</id>
        <imie>Tuli</imie>
        <data_ur>2010-01-15</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">15.8</waga>
        <dlugosc_runa jednostka="mm">10.5</dlugosc_runa>
        <opis>
          Uwielbia się przytulać.
        </opis>
        <szybkosc_marszu jednostka="m/s">15.4</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.8</szybkosc_zjadania_trawy>
      </owca>
    </stado>
  </pastwisko>

  <pastwisko>
    <nazwa>Zielone oastwiska</nazwa>
    <rasa identyfikator="O5" />
    <powierzchnia jednostka="ha">65.8</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Ludmiła</imie>
        <data_ur>2012-09-04</data_ur>
        <plec>K</plec>
        <waga jednostka="kg">100.8</waga>
        <dlugosc_runa jednostka="mm">14.5</dlugosc_runa>
        <opis>
          Piękna długowłosa dama.
        </opis>
        <szybkosc_marszu jednostka="m/s">10.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.4</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>2</id>
        <imie>Bernard</imie>
        <data_ur>2008-12-24</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">27.8</waga>
        <dlugosc_runa jednostka="mm">12.3</dlugosc_runa>
        <opis>
          Wcale nie pies.
        </opis>
        <szybkosc_marszu jednostka="m/s">25.1</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.3</szybkosc_zjadania_trawy>
      </owca>
    </stado>
  </pastwisko>

  <pastwisko>
    <nazwa>Radosna kraina</nazwa>
    <rasa identyfikator="O6" />
    <powierzchnia jednostka="ha">158.5</powierzchnia>
    <stado>
      <owca>
        <id>1</id>
        <imie>Truskawa</imie>
        <data_ur>2010-09-10</data_ur>
        <plec>K</plec>
        <waga jednostka="kg">47.2</waga>
        <dlugosc_runa jednostka="mm">18.6</dlugosc_runa>
        <opis>
          Jakby mogła się przefarbować, to na czerwono.
        </opis>
        <szybkosc_marszu jednostka="m/s">15.2</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.1</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>2</id>
        <imie>Pomarańczka</imie>
        <data_ur>2013-12-31</data_ur>
        <plec>K</plec>
        <waga jednostka="kg">16.9</waga>
        <dlugosc_runa jednostka="mm">15.8</dlugosc_runa>
        <opis>
          Lubi kwaśne.
        </opis>
        <szybkosc_marszu jednostka="m/s">7.5</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.2</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>3</id>
        <imie>Kwas</imie>
        <data_ur>2001-12-10</data_ur>
        <plec>M</plec>
        <waga jednostka="kg">16.5</waga>
        <dlugosc_runa jednostka="mm">25.5</dlugosc_runa>
        <opis>
          Wcale nie lubi kwaśnego.
        </opis>
        <szybkosc_marszu jednostka="m/s">32.5</szybkosc_marszu>
        <szybkosc_zjadania_trawy jednostka="talerz/min">0.8</szybkosc_zjadania_trawy>
      </owca>
      <owca>
        <id>4</id>
        <imie>Mucha</imie>
        <data_ur>1996-11-10</data_ur>
        <plec>K</plec>
